# Python関連の無視するファイル/フォルダ
__pycache__/ # Pythonがバイトコードを保存するキャッシュフォルダ
*.pyc        # Pythonのコンパイル済みファイル
*.pyo
*.pyd
.Python/
env/
venv/        # 仮想環境のフォルダ（これが重要！）
.ipynb_checkpoints
.pytest_cache/

# Streamlit関連の無視するファイル/フォルダ
.streamlit/secrets.toml  # APIキーが含まれるファイル（これが最も重要！）
streamlit_temp/          # Streamlitが一時ファイルを保存するフォルダ

# OSが生成するファイル（WindowsやmacOSで自動的に作られるもの）
.DS_Store    # macOSで生成される隠しファイル
Thumbs.db    # Windowsで生成される隠しファイル